on:
  workflow_dispatch:

jobs:
  release-win-x64-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up temporary directory and copy static files
        run: |
          mkdir ./zip
          cp ./bundle/linux-x64/start.sh ./bundle/linux-x64/README ./zip

      - name: Build archive
        working-directory: zip
        run: |
          tar -cf release.tar start.sh README

      - name: Configure release title and name of zip file
        working-directory: zip
        run: |
          localModuleVersion="$(npm view "@bird-wp07/local-module" version)"
          tarFile="wp07-local-module-linux-x64-v$localModuleVersion.tar"
          mv "release.tar" "$tarFile"
          echo "RELEASE_TITLE=v$localModuleVersion" >>"$GITHUB_ENV"
          echo "RELEASE_ZIP_FILENAME=$tarFile" >>"$GITHUB_ENV"

      - name: Release archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./zip/${{ env.RELEASE_ZIP_FILENAME }}
          name: ${{ env.RELEASE_TITLE }}
          allowUpdates: true
          tag: main

