on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release-linux-x64-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up temporary directory and copy static files
        run: |
          mkdir ./zip
          cp ./bundle/linux-x64/start.sh ./postman.json ./zip

      - name: Compile README.md to README.html
        uses: docker://pandoc/core:2.19
        with:
          args: "--standalone --embed-resources --output ./zip/README.html README.md"

      - name: Create VERSION file
        working-directory: zip
        run: echo "$GITHUB_REF_NAME" | sed 's/^v//' >VERSION

      - name: Build archive
        working-directory: zip
        run: |
          tar -cJf release.tar.xz start.sh postman.json VERSION README.html

      - name: Configure release title and name of zip file
        working-directory: zip
        run: |
          local_module_version="$(npm view "@bird-wp07/local-module" version)"
          archive_filename="wp07-local-module-linux-x64-v$local_module_version.tar.xz"
          mv "release.tar.xz" "$archive_filename"
          echo "RELEASE_ZIP_FILENAME=$archive_filename" >>"$GITHUB_ENV"

      - name: Release archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./zip/${{ env.RELEASE_ZIP_FILENAME }}
          allowUpdates: true
