on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release-linux-x64-bundle:
    runs-on: ubuntu-latest
    env:
     archiveName: wp07-local-module-linux-x64-v${{ GITHUB_REF_NAME }}.tar.xz
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:2.19
        with:
          args: "--standalone --embed-resources --output ./README.html ./README.md"
      - run: |
          mkdir ./zip
          cp ./scripts/bootstrap-linux.sh ./zip/start.sh
          cp ./postman.json ./README.html ./zip
          echo "$GITHUB_REF_NAME" >./zip/VERSION
          cd ./zip && tar -cJf "$archiveName" *

      # If the tag is prefixed with 'test-' we create a pre-release, which,
      # incidentally, won't override the newest release, allowing us to test
      # pipelines ad libitum from any branch.
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./zip/${{ env.archiveName }}
          allowUpdates: true
          prerelease: ${{ startsWith(github.ref_name, 'test-') }}
