on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release-linux-x64-bundle:
    runs-on: ubuntu-latest
    env:
      archiveName: ${{ format('wp07-local-module-linux-x64-{0}.tar.xz', github.ref_name) }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:2.19
        with:
          args: "--standalone --embed-resources --output ./README.html ./docs/README.md"
      - run: |
          mkdir ./zip
          cp ./src/server/openapi.json ./README.html ./scripts/start.sh ./zip
          echo "$GITHUB_REF_NAME" >./zip/VERSION
          cd ./zip && tar -cJf "$archiveName" *

      # If the tag is prefixed with 'test-' we create a pre-release, which,
      # incidentally, won't override the newest release, allowing us to test
      # pipelines ad libitum from any branch.
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./zip/${{ env.archiveName }}
          allowUpdates: true # must be set for the other pipelines to add their archives asynchronously
          prerelease: ${{ startsWith(github.ref_name, 'test-') }}
