on:
  workflow_dispatch:

jobs:
  release-linux-x64-stanalone-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up temporary directory and copy static files
        run: |
          mkdir ./zip
          cp ./bundle/linux-x64/start.sh ./bundle/linux-x64/README ./postman.json ./zip

      - name: Download dependencies and build archive
        working-directory: zip
        run: |
          ./start.sh build_standalone_bundle release.tar.xz

      - name: Configure release title and name of zip file
        working-directory: zip
        run: |
          local_module_version="$(npm view "@bird-wp07/local-module" version)"
          archive_filename="wp07-local-module-linux-x64-standalone-v$local_module_version.tar.xz"
          mv "release.tar.xz" "$archive_filename"
          echo "RELEASE_TITLE=v$local_module_version" >>"$GITHUB_ENV"
          echo "RELEASE_ZIP_FILENAME=$archive_filename" >>"$GITHUB_ENV"

      - name: Release archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./zip/${{ env.RELEASE_ZIP_FILENAME }}
          name: ${{ env.RELEASE_TITLE }}
          allowUpdates: true
          tag: main

