on:
  push:
    branches:
      - main

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - run: |
         curl -X POST \
         -H 'Authorization: Bearer ${{ secrets.DAAD_WP07_PAT }}' \
         -H 'Accept: application/vnd.github.v3+json' \
         https://api.github.com/repos/bird-wp07/win10-x64-bundle/actions/workflows/deploy.yml/dispatches \
         -d '{"ref": "main"}'
