on:
  push:
    branches:
      - main

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger my downstream workflow
        run: |
          curl -XPOST -u '${{ secrets.GIT_CREDENTIALS }}' -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/bird-wp07/release-win-x64-bundle/main.yml/dispatches --data '{"ref": "main" }'
