on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release-win-x64-bundle:
    runs-on: windows-latest
    env:
      archiveName: ${{ format('wp07-local-module-windows-x64-{0}.zip', github.ref_name) }}
    steps:
      - uses: actions/checkout@v3

      - run: |
          New-Item -Path . -Name ".\zip\" -ItemType "directory"
          Copy-Item @(".\bundle\win10-x64\*", ".\src\server\openapi.json") -Destination ".\zip\"
          Set-Content -Path .\zip\VERSION -Value $env:GITHUB_REF_NAME
          choco install --yes pandoc
          pandoc --standalone --embed-resources --output=./zip/README.html ./docs/README.md

      - shell: powershell # see https://github.com/MScholtes/PS2EXE/issues/82
        working-directory: zip
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe
          Invoke-ps2exe -inputFile .\start.ps1 -iconFile ..\bundle\win10-x64\bird.ico -outputFile .\start.exe

        # FIXME: Remove bird.ico from archive
      - name: Build archive
        working-directory: zip
        run: |
          7z a $env:archiveName *

      - uses: ncipollo/release-action@v1
        with:
          artifacts: .\zip\${{ env.archiveName }}
          allowUpdates: true
          prerelease: ${{ startsWith(github.ref_name, 'test-') }}
