on:
  workflow_dispatch:

jobs:
  release-win-x64-bundle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up temporary directory and download and extract standalone node
        run: |
          New-Item -Path . -Name ".\zip\" -ItemType "directory"
          Copy-Item ".\bundle\win10-x64\start.ps1" -Destination ".\zip\"
          cd ".\zip\"
          curl -o .\node-v18.12.1-win-x64.zip https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip
          7z x .\node-v18.12.1-win-x64.zip
          Add-Content $env:GITHUB_PATH $(Resolve-Path .\node-v18.12.1-win-x64\)

      - name: Install local-module npm package
        run: |
          cd ".\zip\"
          npm install --prefix . @bird-wp07/local-module

      - name: Download and unpack standalone DSS into .\zip\dss\
        run: |
          cd ".\zip\"
          curl -o .\dss-standalone.zip "https://ec.europa.eu/digital-building-blocks/artifact/repository/esignaturedss/eu/europa/ec/joinup/sd-dss/dss-demo-bundle/5.11.1/dss-demo-bundle-5.11.1.zip"
          7z x .\dss-standalone.zip

      - name: Create zipfile
        run: |
          cd ".\zip\"
          7z a release.zip .\node-v18.12.1-win-x64\ \dss-demo-bundle-5.11.1\ .\node_modules\ .\package.json .\start.ps1

      - name: Configure release title and name of zip file
        run: |
          cd ".\zip\"
          $dateString = Get-Date -Format yyyy-MM-ddTHH:mm:ssK
          $zipFile = "wp07-local-module-win10-x64.zip"
          Rename-Item -Path ".\release.zip" -NewName $zipFile
          Add-Content $env:GITHUB_ENV "RELEASE_TITLE=wp07-local-module-win10-x64-v$($dateString)"
          Add-Content $env:GITHUB_ENV "RELEASE_ZIP_FILENAME=$($zipFile)"

      - name: Release archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: .\zip\${{ env.RELEASE_ZIP_FILENAME }}
          name: ${{ env.RELEASE_TITLE }}
          allowUpdates: true
          tag: main
