on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release-win-x64-standalone-bundle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up temporary directory and copy static files
        run: |
          New-Item -Path . -Name ".\zip\" -ItemType "directory"
          Copy-Item ".\bundle\win10-x64\start.ps1" -Destination ".\zip\"
          Copy-Item ".\bundle\win10-x64\README" -Destination ".\zip\"
          Copy-Item ".\postman.json" -Destination ".\zip\"

      - name: Compile .exe from pwsh script
        shell: powershell
        working-directory: zip
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe
          Invoke-ps2exe .\start.ps1 .\start.exe

      - name: Create VERSION file
        working-directory: zip
        run: Set-Content -Path VERSION -Value $env:GITHUB_REF_NAME.substring(1)

      - name: Install standalone dss
        working-directory: zip
        run: |
          & .\start.ps1 install-dependencies dss

      - name: Install standalone node
        working-directory: zip
        run: |
          & .\start.ps1 install-dependencies node

      - name: Install local-module npm package
        working-directory: zip
        run: |
          echo $env:GITHUB_REF
          echo $env:GITHUB_REF_NAME
          & .\start.ps1 install-dependencies local-module $env:GITHUB_REF_NAME.substring(1)

      - name: Build archive
        working-directory: zip
        run: |
          7z a release.zip ".\local-module" ".\dss-demo-bundle-5.11" ".\node-v18.12.1-win-x64" ".\start.ps1" ".\start.exe" ".\README" ".\postman.json" ".\VERSION"

      - name: Configure release title and name of zip file
        working-directory: zip
        run: |
          $localModuleVersion = npm view "@bird-wp07/local-module" version
          $zipFile = "wp07-local-module-win10-x64-standalone-v$localModuleVersion.zip"
          Rename-Item -Path ".\release.zip" -NewName $zipFile
          Add-Content $env:GITHUB_ENV "RELEASE_ZIP_FILENAME=$zipFile"

      - name: Release archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: .\zip\${{ env.RELEASE_ZIP_FILENAME }}
          allowUpdates: true
